server:
  port: 8088
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 2000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000




#  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000
#spring.cloud.loadbalancer.retry.enabled: true
#  ribbon.ReadTimeout: 60000
#  ribbon.ConnectTimeout: 60000